<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
    <LangVersion>8</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.1|AnyCPU'">
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.1|AnyCPU'">
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Engine\Scheduler\FastGameTask.cs" />
    <Compile Remove="Engine\Scheduler\FastScheduler.cs" />
    <Compile Remove="Systems\Harvesting\ResourceTypes.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameData\GameData.csproj" />
    <ProjectReference Include="..\Serializer\Serializer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MemoryPack">
      <HintPath>..\..\PreCompiledLibraries\MemoryPack\MemoryPack.dll</HintPath>
    </Reference>
    <Reference Include="MemoryPack.Core">
      <HintPath>..\..\PreCompiledLibraries\MemoryPack\MemoryPack.Core.dll</HintPath>
    </Reference>
    <Reference Include="MemoryPack.Generator">
      <HintPath>..\..\PreCompiledLibraries\MemoryPack\MemoryPack.Generator.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Condition="$([MSBuild]::IsOSPlatform('OSX'))" Command="cp -vf $(TargetPath) $(SolutionDir)/../LisergyClient/LisergyClient/Assets/Plugins/Game.dll" />
    <Exec Condition="$([MSBuild]::IsOSPlatform('Linux'))" Command="cp -vf $(TargetPath) $(SolutionDir)/../LisergyClient/LisergyClient/Assets/Plugins/Game.dll" />
    <Exec Condition="$([MSBuild]::IsOSPlatform('Windows'))" Command="xcopy /y /s /f $(TargetPath) $(SolutionDir)\..\LisergyClient\LisergyClient\Assets\Plugins\Game.dll*" />
  </Target>

</Project>
