/* AUTO GENERATED CODE BY AddressableGeneration.cs */
using System.Collections.Generic;
namespace GameAssets
{

	public enum UIScreen
	{
		HealthBar = 0,
		PartyButton = 1,
		RadialProgress = 2,
		BattleScreen = 3,
		LoginScreen = 4,
		PartySelectBar = 5,
		UnitActions = 6,
		BattleNotification = 7,
		TransitionScreen = 8,
	}


	public enum TilePrefab
	{
		Floor = 9,
		Fog50 = 10,
		FogBlack = 11,
		FogBorderContainer = 12,
		Forest = 13,
		Mountain = 14,
		Plains = 15,
		Plains_Low = 16,
		Plane = 17,
		Tree = 18,
		Tree_Low = 19,
		Water = 20,
		Floor_Low = 21,
	}


	public enum MapObjectPrefab
	{
		Cursor = 22,
		UnitCursor = 23,
	}


	public enum MapFX
	{
		BattleEffect = 24,
		HalfPath = 25,
	}


	public enum BuildingPrefab
	{
		Castle = 26,
		Dungeon = 27,
		SimpleHouse = 28,
	}


	public enum UnitPrefab
	{
		Mage = 29,
		Knight = 30,
		Rogue = 31,
	}


	public enum UISetting
	{
		PanelSettings = 32,
	}


	public enum SoundFX
	{
		Button_click = 33,
		Slime8 = 34,
		Slime9 = 35,
		Slime6 = 36,
		Slime2 = 37,
		Slime1 = 38,
		Slime10 = 39,
		Slime4 = 40,
		Slime5 = 41,
		Slime3 = 42,
		Slime7 = 43,
		Sharp_echo = 44,
		Negative = 45,
		Positive = 46,
		Misc_menu = 47,
		Misc_menu_3 = 48,
		Negative_2 = 49,
		Save = 50,
		Load = 51,
		Click_2 = 52,
		Misc_menu_4 = 53,
		Misc_sound = 54,
		Misc_menu_2 = 55,
		Click = 56,
		Interface2 = 57,
		Interface1 = 58,
		Interface6 = 59,
		Interface4 = 60,
		Interface5 = 61,
		Interface3 = 62,
		Bottle = 63,
		Coin2 = 64,
		Chainmail1 = 65,
		Bubble2 = 66,
		Metal_ringing = 67,
		Metal_small1 = 68,
		Coin = 69,
		Chainmail2 = 70,
		Wood_small = 71,
		Cloth = 72,
		Metal_small3 = 73,
		Coin3 = 74,
		Bubble3 = 75,
		Bubble = 76,
		Beads = 77,
		Metal_small2 = 78,
		Armor_light = 79,
		Cloth_heavy = 80,
		DrawKnife3 = 81,
		BookPlace2 = 82,
		Cloth1 = 83,
		Footstep09 = 84,
		HandleCoins = 85,
		DoorClose_4 = 86,
		Footstep08 = 87,
		BookPlace1 = 88,
		DropLeather = 89,
		MetalClick = 90,
		HandleCoins2 = 91,
		MetalLatch = 92,
		BookPlace3 = 93,
		KnifeSlice2 = 94,
		DrawKnife1 = 95,
		Cloth2 = 96,
		DoorOpen_1 = 97,
		Creak1 = 98,
		Cloth4 = 99,
		DrawKnife2 = 100,
		MetalPot3 = 101,
		ClothBelt = 102,
		KnifeSlice = 103,
		DoorOpen_2 = 104,
		ClothBelt2 = 105,
		BeltHandle1 = 106,
		Cloth3 = 107,
		DoorClose_2 = 108,
		DoorClose_1 = 109,
		Footstep03 = 110,
		BookFlip2 = 111,
		MetalPot1 = 112,
		BookFlip1 = 113,
		Footstep01 = 114,
		HandleSmallLeather2 = 115,
		Footstep02 = 116,
		Footstep00 = 117,
		BookClose = 118,
		BeltHandle2 = 119,
		Creak2 = 120,
		MetalPot2 = 121,
		Footstep06 = 122,
		Chop = 123,
		DoorClose_3 = 124,
		BookOpen = 125,
		Creak3 = 126,
		Footstep07 = 127,
		BookFlip3 = 128,
		Footstep05 = 129,
		HandleSmallLeather = 130,
		Footstep04 = 131,
		Hit21_mp3 = 132,
		Hit20_mp3 = 133,
		Hit14_mp3 = 134,
		Hit02_mp3 = 135,
		Hit10_mp3 = 136,
		Hit11_mp3 = 137,
		Hit28_mp3 = 138,
		Hit17_mp3 = 139,
		Hit24_mp3 = 140,
		Hit03_mp3 = 141,
		Hit06_mp3 = 142,
		Hit12_mp3 = 143,
		Hit34_mp3 = 144,
		Hit27_mp3 = 145,
		Hit25_mp3 = 146,
		Hit31_mp3 = 147,
		Hit15_mp3 = 148,
		Hit29_mp3 = 149,
		Hit36_mp3 = 150,
		Hit18_mp3 = 151,
		Hit22_mp3 = 152,
		Hit05_mp3 = 153,
		Hit32_mp3 = 154,
		Hit30_mp3 = 155,
		Hit01_mp3 = 156,
		Hit08_mp3 = 157,
		Hit35_mp3 = 158,
		Hit13_mp3 = 159,
		Hit09_mp3 = 160,
		Hit04_mp3 = 161,
		Hit33_mp3 = 162,
		Hit16_mp3 = 163,
		Hit19_mp3 = 164,
		Hit37_mp3 = 165,
		Hit26_mp3 = 166,
		Hit07_mp3 = 167,
		Hit23_mp3 = 168,
		Magic1 = 169,
		Spell = 170,
		Swing = 171,
		Swing2 = 172,
		Swing3 = 173,
		Sword_unsheathe = 174,
		Sword_unsheathe2 = 175,
		Sword_unsheathe3 = 176,
		Sword_unsheathe4 = 177,
		Sword_unsheathe5 = 178,
		Ogre1 = 179,
		Ogre2 = 180,
		Ogre3 = 181,
		Ogre4 = 182,
		Ogre5 = 183,
	}


	public enum Generic
	{
		Alexander_nakarada_tavern_loop_one = 184,
		Alexander_nakarada_the_vikings = 185,
	}


	public enum SpritePrefab
	{
		Badge_mage = 186,
		Badge_necro = 187,
		Alchemy = 188,
		Badge_assassin = 189,
		Badge_barbarian = 190,
		Badge_hunter = 191,
		Badge_paladin = 192,
		Badge_priest = 193,
		Badge_rogue = 194,
		Badge_warrior = 195,
		Blacksmith_craft = 196,
		Carpentry = 197,
		Diplomacy = 198,
		Farming = 199,
		Fishing = 200,
		Hunting = 201,
		Mining = 202,
		Tailoring = 203,
	}

	public static class AddressIdMap
	{
		public static IReadOnlyDictionary<int, string> IdMap = new Dictionary<int, string>() {
			{ 0, "Assets/Addressables/UIScreens/Components/HealthBar.uxml"},
			{ 1, "Assets/Addressables/UIScreens/Components/PartyButton.uxml"},
			{ 2, "Assets/Addressables/UIScreens/Components/RadialProgress.uxml"},
			{ 3, "Assets/Addressables/UIScreens/BattleScreen.uxml"},
			{ 4, "Assets/Addressables/UIScreens/LoginScreen.uxml"},
			{ 5, "Assets/Addressables/UIScreens/PartySelectBar.uxml"},
			{ 6, "Assets/Addressables/UIScreens/UnitActions.uxml"},
			{ 7, "Assets/Addressables/UIScreens/Notifications/BattleNotification.uxml"},
			{ 8, "Assets/Addressables/UIScreens/TransitionScreen.uxml"},
			{ 9, "Assets/Addressables/Prefabs/Tiles/Floor.prefab"},
			{ 10, "Assets/Addressables/Prefabs/Tiles/Fog50.prefab"},
			{ 11, "Assets/Addressables/Prefabs/Tiles/FogBlack.prefab"},
			{ 12, "Assets/Addressables/Prefabs/Tiles/FogBorderContainer.prefab"},
			{ 13, "Assets/Addressables/Prefabs/Tiles/Forest.prefab"},
			{ 14, "Assets/Addressables/Prefabs/Tiles/Mountain.prefab"},
			{ 15, "Assets/Addressables/Prefabs/Tiles/Plains.prefab"},
			{ 16, "Assets/Addressables/Prefabs/Tiles/Plains_Mobile.prefab"},
			{ 17, "Assets/Addressables/Prefabs/Tiles/Plane.prefab"},
			{ 18, "Assets/Addressables/Prefabs/Tiles/Tree.prefab"},
			{ 19, "Assets/Addressables/Prefabs/Tiles/Tree_Mobile.prefab"},
			{ 20, "Assets/Addressables/Prefabs/Tiles/Water.prefab"},
			{ 21, "Assets/Addressables/Prefabs/Tiles/Floor_Low.prefab"},
			{ 22, "Assets/Addressables/Prefabs/MapObjects/Cursor.prefab"},
			{ 23, "Assets/Addressables/Prefabs/MapObjects/UnitCursor.prefab"},
			{ 24, "Assets/Addressables/Prefabs/Effects/BattleEffect.prefab"},
			{ 25, "Assets/Addressables/Prefabs/Effects/HalfPath.prefab"},
			{ 26, "Assets/Addressables/Prefabs/Buildings/Castle.prefab"},
			{ 27, "Assets/Addressables/Prefabs/Buildings/dungeon.prefab"},
			{ 28, "Assets/Addressables/Prefabs/Buildings/SimpleHouse.prefab"},
			{ 29, "Assets/Addressables/Prefabs/Units/Mage.prefab"},
			{ 30, "Assets/Addressables/Prefabs/Units/Knight.prefab"},
			{ 31, "Assets/Addressables/Prefabs/Units/Rogue.prefab"},
			{ 32, "Assets/Addressables/UISettings/PanelSettings.asset"},
			{ 33, "Assets/Addressables/Audio/Sfx/button_click.mp3"},
			{ 34, "Assets/Addressables/Audio/Sfx/NPC/slime/slime8.wav"},
			{ 35, "Assets/Addressables/Audio/Sfx/NPC/slime/slime9.wav"},
			{ 36, "Assets/Addressables/Audio/Sfx/NPC/slime/slime6.wav"},
			{ 37, "Assets/Addressables/Audio/Sfx/NPC/slime/slime2.wav"},
			{ 38, "Assets/Addressables/Audio/Sfx/NPC/slime/slime1.wav"},
			{ 39, "Assets/Addressables/Audio/Sfx/NPC/slime/slime10.wav"},
			{ 40, "Assets/Addressables/Audio/Sfx/NPC/slime/slime4.wav"},
			{ 41, "Assets/Addressables/Audio/Sfx/NPC/slime/slime5.wav"},
			{ 42, "Assets/Addressables/Audio/Sfx/NPC/slime/slime3.wav"},
			{ 43, "Assets/Addressables/Audio/Sfx/NPC/slime/slime7.wav"},
			{ 44, "Assets/Addressables/Audio/Sfx/gui/sharp_echo.wav"},
			{ 45, "Assets/Addressables/Audio/Sfx/gui/negative.wav"},
			{ 46, "Assets/Addressables/Audio/Sfx/gui/positive.wav"},
			{ 47, "Assets/Addressables/Audio/Sfx/gui/misc_menu.wav"},
			{ 48, "Assets/Addressables/Audio/Sfx/gui/misc_menu_3.wav"},
			{ 49, "Assets/Addressables/Audio/Sfx/gui/negative_2.wav"},
			{ 50, "Assets/Addressables/Audio/Sfx/gui/save.wav"},
			{ 51, "Assets/Addressables/Audio/Sfx/gui/load.wav"},
			{ 52, "Assets/Addressables/Audio/Sfx/gui/click_2.wav"},
			{ 53, "Assets/Addressables/Audio/Sfx/gui/misc_menu_4.wav"},
			{ 54, "Assets/Addressables/Audio/Sfx/gui/misc_sound.wav"},
			{ 55, "Assets/Addressables/Audio/Sfx/gui/misc_menu_2.wav"},
			{ 56, "Assets/Addressables/Audio/Sfx/gui/click.wav"},
			{ 57, "Assets/Addressables/Audio/Sfx/interface/interface2.wav"},
			{ 58, "Assets/Addressables/Audio/Sfx/interface/interface1.wav"},
			{ 59, "Assets/Addressables/Audio/Sfx/interface/interface6.wav"},
			{ 60, "Assets/Addressables/Audio/Sfx/interface/interface4.wav"},
			{ 61, "Assets/Addressables/Audio/Sfx/interface/interface5.wav"},
			{ 62, "Assets/Addressables/Audio/Sfx/interface/interface3.wav"},
			{ 63, "Assets/Addressables/Audio/Sfx/inventory/bottle.wav"},
			{ 64, "Assets/Addressables/Audio/Sfx/inventory/coin2.wav"},
			{ 65, "Assets/Addressables/Audio/Sfx/inventory/chainmail1.wav"},
			{ 66, "Assets/Addressables/Audio/Sfx/inventory/bubble2.wav"},
			{ 67, "Assets/Addressables/Audio/Sfx/inventory/metal-ringing.wav"},
			{ 68, "Assets/Addressables/Audio/Sfx/inventory/metal-small1.wav"},
			{ 69, "Assets/Addressables/Audio/Sfx/inventory/coin.wav"},
			{ 70, "Assets/Addressables/Audio/Sfx/inventory/chainmail2.wav"},
			{ 71, "Assets/Addressables/Audio/Sfx/inventory/wood-small.wav"},
			{ 72, "Assets/Addressables/Audio/Sfx/inventory/cloth.wav"},
			{ 73, "Assets/Addressables/Audio/Sfx/inventory/metal-small3.wav"},
			{ 74, "Assets/Addressables/Audio/Sfx/inventory/coin3.wav"},
			{ 75, "Assets/Addressables/Audio/Sfx/inventory/bubble3.wav"},
			{ 76, "Assets/Addressables/Audio/Sfx/inventory/bubble.wav"},
			{ 77, "Assets/Addressables/Audio/Sfx/inventory/beads.wav"},
			{ 78, "Assets/Addressables/Audio/Sfx/inventory/metal-small2.wav"},
			{ 79, "Assets/Addressables/Audio/Sfx/inventory/armor-light.wav"},
			{ 80, "Assets/Addressables/Audio/Sfx/inventory/cloth-heavy.wav"},
			{ 81, "Assets/Addressables/Audio/Sfx/rpg/drawKnife3.ogg"},
			{ 82, "Assets/Addressables/Audio/Sfx/rpg/bookPlace2.ogg"},
			{ 83, "Assets/Addressables/Audio/Sfx/rpg/cloth1.ogg"},
			{ 84, "Assets/Addressables/Audio/Sfx/rpg/footstep09.ogg"},
			{ 85, "Assets/Addressables/Audio/Sfx/rpg/handleCoins.ogg"},
			{ 86, "Assets/Addressables/Audio/Sfx/rpg/doorClose_4.ogg"},
			{ 87, "Assets/Addressables/Audio/Sfx/rpg/footstep08.ogg"},
			{ 88, "Assets/Addressables/Audio/Sfx/rpg/bookPlace1.ogg"},
			{ 89, "Assets/Addressables/Audio/Sfx/rpg/dropLeather.ogg"},
			{ 90, "Assets/Addressables/Audio/Sfx/rpg/metalClick.ogg"},
			{ 91, "Assets/Addressables/Audio/Sfx/rpg/handleCoins2.ogg"},
			{ 92, "Assets/Addressables/Audio/Sfx/rpg/metalLatch.ogg"},
			{ 93, "Assets/Addressables/Audio/Sfx/rpg/bookPlace3.ogg"},
			{ 94, "Assets/Addressables/Audio/Sfx/rpg/knifeSlice2.ogg"},
			{ 95, "Assets/Addressables/Audio/Sfx/rpg/drawKnife1.ogg"},
			{ 96, "Assets/Addressables/Audio/Sfx/rpg/cloth2.ogg"},
			{ 97, "Assets/Addressables/Audio/Sfx/rpg/doorOpen_1.ogg"},
			{ 98, "Assets/Addressables/Audio/Sfx/rpg/creak1.ogg"},
			{ 99, "Assets/Addressables/Audio/Sfx/rpg/cloth4.ogg"},
			{ 100, "Assets/Addressables/Audio/Sfx/rpg/drawKnife2.ogg"},
			{ 101, "Assets/Addressables/Audio/Sfx/rpg/metalPot3.ogg"},
			{ 102, "Assets/Addressables/Audio/Sfx/rpg/clothBelt.ogg"},
			{ 103, "Assets/Addressables/Audio/Sfx/rpg/knifeSlice.ogg"},
			{ 104, "Assets/Addressables/Audio/Sfx/rpg/doorOpen_2.ogg"},
			{ 105, "Assets/Addressables/Audio/Sfx/rpg/clothBelt2.ogg"},
			{ 106, "Assets/Addressables/Audio/Sfx/rpg/beltHandle1.ogg"},
			{ 107, "Assets/Addressables/Audio/Sfx/rpg/cloth3.ogg"},
			{ 108, "Assets/Addressables/Audio/Sfx/rpg/doorClose_2.ogg"},
			{ 109, "Assets/Addressables/Audio/Sfx/rpg/doorClose_1.ogg"},
			{ 110, "Assets/Addressables/Audio/Sfx/rpg/footstep03.ogg"},
			{ 111, "Assets/Addressables/Audio/Sfx/rpg/bookFlip2.ogg"},
			{ 112, "Assets/Addressables/Audio/Sfx/rpg/metalPot1.ogg"},
			{ 113, "Assets/Addressables/Audio/Sfx/rpg/bookFlip1.ogg"},
			{ 114, "Assets/Addressables/Audio/Sfx/rpg/footstep01.ogg"},
			{ 115, "Assets/Addressables/Audio/Sfx/rpg/handleSmallLeather2.ogg"},
			{ 116, "Assets/Addressables/Audio/Sfx/rpg/footstep02.ogg"},
			{ 117, "Assets/Addressables/Audio/Sfx/rpg/footstep00.ogg"},
			{ 118, "Assets/Addressables/Audio/Sfx/rpg/bookClose.ogg"},
			{ 119, "Assets/Addressables/Audio/Sfx/rpg/beltHandle2.ogg"},
			{ 120, "Assets/Addressables/Audio/Sfx/rpg/creak2.ogg"},
			{ 121, "Assets/Addressables/Audio/Sfx/rpg/metalPot2.ogg"},
			{ 122, "Assets/Addressables/Audio/Sfx/rpg/footstep06.ogg"},
			{ 123, "Assets/Addressables/Audio/Sfx/rpg/chop.ogg"},
			{ 124, "Assets/Addressables/Audio/Sfx/rpg/doorClose_3.ogg"},
			{ 125, "Assets/Addressables/Audio/Sfx/rpg/bookOpen.ogg"},
			{ 126, "Assets/Addressables/Audio/Sfx/rpg/creak3.ogg"},
			{ 127, "Assets/Addressables/Audio/Sfx/rpg/footstep07.ogg"},
			{ 128, "Assets/Addressables/Audio/Sfx/rpg/bookFlip3.ogg"},
			{ 129, "Assets/Addressables/Audio/Sfx/rpg/footstep05.ogg"},
			{ 130, "Assets/Addressables/Audio/Sfx/rpg/handleSmallLeather.ogg"},
			{ 131, "Assets/Addressables/Audio/Sfx/rpg/footstep04.ogg"},
			{ 132, "Assets/Addressables/Audio/Sfx/hits/hit21.mp3.flac"},
			{ 133, "Assets/Addressables/Audio/Sfx/hits/hit20.mp3.flac"},
			{ 134, "Assets/Addressables/Audio/Sfx/hits/hit14.mp3.flac"},
			{ 135, "Assets/Addressables/Audio/Sfx/hits/hit02.mp3.flac"},
			{ 136, "Assets/Addressables/Audio/Sfx/hits/hit10.mp3.flac"},
			{ 137, "Assets/Addressables/Audio/Sfx/hits/hit11.mp3.flac"},
			{ 138, "Assets/Addressables/Audio/Sfx/hits/hit28.mp3.flac"},
			{ 139, "Assets/Addressables/Audio/Sfx/hits/hit17.mp3.flac"},
			{ 140, "Assets/Addressables/Audio/Sfx/hits/hit24.mp3.flac"},
			{ 141, "Assets/Addressables/Audio/Sfx/hits/hit03.mp3.flac"},
			{ 142, "Assets/Addressables/Audio/Sfx/hits/hit06.mp3.flac"},
			{ 143, "Assets/Addressables/Audio/Sfx/hits/hit12.mp3.flac"},
			{ 144, "Assets/Addressables/Audio/Sfx/hits/hit34.mp3.flac"},
			{ 145, "Assets/Addressables/Audio/Sfx/hits/hit27.mp3.flac"},
			{ 146, "Assets/Addressables/Audio/Sfx/hits/hit25.mp3.flac"},
			{ 147, "Assets/Addressables/Audio/Sfx/hits/hit31.mp3.flac"},
			{ 148, "Assets/Addressables/Audio/Sfx/hits/hit15.mp3.flac"},
			{ 149, "Assets/Addressables/Audio/Sfx/hits/hit29.mp3.flac"},
			{ 150, "Assets/Addressables/Audio/Sfx/hits/hit36.mp3.flac"},
			{ 151, "Assets/Addressables/Audio/Sfx/hits/hit18.mp3.flac"},
			{ 152, "Assets/Addressables/Audio/Sfx/hits/hit22.mp3.flac"},
			{ 153, "Assets/Addressables/Audio/Sfx/hits/hit05.mp3.flac"},
			{ 154, "Assets/Addressables/Audio/Sfx/hits/hit32.mp3.flac"},
			{ 155, "Assets/Addressables/Audio/Sfx/hits/hit30.mp3.flac"},
			{ 156, "Assets/Addressables/Audio/Sfx/hits/hit01.mp3.flac"},
			{ 157, "Assets/Addressables/Audio/Sfx/hits/hit08.mp3.flac"},
			{ 158, "Assets/Addressables/Audio/Sfx/hits/hit35.mp3.flac"},
			{ 159, "Assets/Addressables/Audio/Sfx/hits/hit13.mp3.flac"},
			{ 160, "Assets/Addressables/Audio/Sfx/hits/hit09.mp3.flac"},
			{ 161, "Assets/Addressables/Audio/Sfx/hits/hit04.mp3.flac"},
			{ 162, "Assets/Addressables/Audio/Sfx/hits/hit33.mp3.flac"},
			{ 163, "Assets/Addressables/Audio/Sfx/hits/hit16.mp3.flac"},
			{ 164, "Assets/Addressables/Audio/Sfx/hits/hit19.mp3.flac"},
			{ 165, "Assets/Addressables/Audio/Sfx/hits/hit37.mp3.flac"},
			{ 166, "Assets/Addressables/Audio/Sfx/hits/hit26.mp3.flac"},
			{ 167, "Assets/Addressables/Audio/Sfx/hits/hit07.mp3.flac"},
			{ 168, "Assets/Addressables/Audio/Sfx/hits/hit23.mp3.flac"},
			{ 169, "Assets/Addressables/Audio/Sfx/battle/magic1.wav"},
			{ 170, "Assets/Addressables/Audio/Sfx/battle/spell.wav"},
			{ 171, "Assets/Addressables/Audio/Sfx/battle/swing.wav"},
			{ 172, "Assets/Addressables/Audio/Sfx/battle/swing2.wav"},
			{ 173, "Assets/Addressables/Audio/Sfx/battle/swing3.wav"},
			{ 174, "Assets/Addressables/Audio/Sfx/battle/sword-unsheathe.wav"},
			{ 175, "Assets/Addressables/Audio/Sfx/battle/sword-unsheathe2.wav"},
			{ 176, "Assets/Addressables/Audio/Sfx/battle/sword-unsheathe3.wav"},
			{ 177, "Assets/Addressables/Audio/Sfx/battle/sword-unsheathe4.wav"},
			{ 178, "Assets/Addressables/Audio/Sfx/battle/sword-unsheathe5.wav"},
			{ 179, "Assets/Addressables/Audio/Sfx/NPC/ogre/ogre1.wav"},
			{ 180, "Assets/Addressables/Audio/Sfx/NPC/ogre/ogre2.wav"},
			{ 181, "Assets/Addressables/Audio/Sfx/NPC/ogre/ogre3.wav"},
			{ 182, "Assets/Addressables/Audio/Sfx/NPC/ogre/ogre4.wav"},
			{ 183, "Assets/Addressables/Audio/Sfx/NPC/ogre/ogre5.wav"},
			{ 184, "Assets/Addressables/Audio/Bgm/alexander-nakarada-tavern-loop-one.mp3"},
			{ 185, "Assets/Addressables/Audio/Bgm/alexander-nakarada-the-vikings.mp3"},
			{ 186, "Assets/Addressables/Sprites/Badges/Badge_mage.png"},
			{ 187, "Assets/Addressables/Sprites/Badges/Badge_necro.png"},
			{ 188, "Assets/Addressables/Sprites/Badges/alchemy.png"},
			{ 189, "Assets/Addressables/Sprites/Badges/Badge_assassin.png"},
			{ 190, "Assets/Addressables/Sprites/Badges/Badge_barbarian.png"},
			{ 191, "Assets/Addressables/Sprites/Badges/Badge_hunter.png"},
			{ 192, "Assets/Addressables/Sprites/Badges/Badge_paladin.png"},
			{ 193, "Assets/Addressables/Sprites/Badges/Badge_priest.PNG"},
			{ 194, "Assets/Addressables/Sprites/Badges/Badge_rogue.png"},
			{ 195, "Assets/Addressables/Sprites/Badges/Badge_warrior.png"},
			{ 196, "Assets/Addressables/Sprites/Badges/blacksmith_craft.png"},
			{ 197, "Assets/Addressables/Sprites/Badges/carpentry.png"},
			{ 198, "Assets/Addressables/Sprites/Badges/diplomacy.png"},
			{ 199, "Assets/Addressables/Sprites/Badges/farming.png"},
			{ 200, "Assets/Addressables/Sprites/Badges/fishing.PNG"},
			{ 201, "Assets/Addressables/Sprites/Badges/hunting.png"},
			{ 202, "Assets/Addressables/Sprites/Badges/mining.png"},
			{ 203, "Assets/Addressables/Sprites/Badges/tailoring.png"},
		};
	}
}
